#!/bin/sh
set -e

CUR=$(pwd)
INPUTS="${CUR}/aoc-inputs/2022"

cd repo
INSTALLDIR=../ make install
cd ../

# inputs look like
# aoc-inputs/year/day/files
i=1
while [ $i -ne 26 ]
do
  export DAY="${i}"
  echo ""
  echo "--- Checking inputs for day ${i} ---"

  padded=`printf %03d $i`
  input_dir="${INPUTS}/day_${padded}"
  solutions="${input_dir}/solutions.json"
  export SOLUTION_FILE="${solutions}"

  if [ ! -d "${input_dir}" ]; then
    echo "no inputs for day ${i}, breaking"
    break
  fi

  input_list=$(find "${input_dir}" -name "input-*" -exec basename {} \;)
  echo "detected the following inputs for day ${i}: ${input_list}"

  var_prefix="AOC_INPUT=${input_dir}"

  # get the list of "executables"
  short_padded=`printf %02d $i`

  echo "12121" > "testfilename"

  if ./aoc -i testfilename -d $i 2>&1 | grep -q 'do not exist'; then
    echo "no solution implemented for day ${i}"
    break
  fi

  for name in $input_list
  do
    export INPUT_NAME="${name}"
    echo "Checking ${name}"
    solution=$(./aoc -i "${input_dir}/${name}" -d $i -j)
    echo "${solution}"
    if [ ! -f "${solutions}" ]; then
      echo "no solutions for day ${i}, skipping check"
    else
      echo "checking solution against recorded solution"
      echo "${solution}" | python ci/scripts/check_solution.py
    fi
    echo ""
  done

  # un-tar any compressed files, if necessary
  find "${input_dir}" -type f -name "*.tar.gz" -exec tar -xvf {} -C "${input_dir}" \; || true

  # large benchmarks
  large_input_list=$(find "${input_dir}" -type f -regextype sed -regex ".*/challenge-input-[^.]*" -exec basename {} \;)
  echo "detected the following challenge inputs for day ${i}: ${large_input_list}"

  for name in $large_input_list
  do
    export INPUT_NAME="${name}"
    echo "Checking ${name}"
    solution=$(./aoc -i "${input_dir}/${name}" -d $i -j)
    echo "${solution}"
    if [ ! -f "${solutions}" ]; then
      echo "no solutions for day ${i}, skipping check"
    else
      echo "checking solution against recorded solution"
      set +e
      echo "${solution}" | python ci/scripts/check_solution.py
      set -e
    fi
    echo ""
  done

  i=`expr $i + 1`
done
