#!/bin/sh
set -ex

git config --global user.name "papercode ci"
git config --global user.email "matt@questionable.engineering"

# make the working repo
git clone aoc-inputs modified-aoc-inputs

i=1
while [ $i -ne 26 ]
do
  padded=`printf %03d $i`
  target="modified-aoc-inputs/2021/day_${padded}"
  mkdir -p $target

  # Find all of the relevant input files. This can't really be generic
  # since everyone sort of stores these in their own way

  # mattcl
  find "mattcl/examples" -type d -name "${padded}*" -exec cp "{}/input" "${target}/input-mattcl" \;

  # lanjian
  padded=`printf %02d $i`
  source="lanjian/inputs/day_${padded}"
  if [ -f $source ]; then
    cp $source "${target}/input-lanjian"
  fi

  # nathanwang2

  if [ -d "nathanwang2/day${i}" ]; then
    find "nathanwang2/day${i}" -name "*.txt" -exec cp "{}" "${target}/input-nathanwang2" \;
  fi

  i=`expr $i + 1`
done

cd modified-aoc-inputs

git add .

if [ -z "$(git status --porcelain)" ]; then
  echo "Working directory clean"
else
  git commit -a -m "automated: updated inputs from sources"
fi
