#!/bin/sh
set -ex

git config --global user.name "papercode ci"
git config --global user.email "matt@questionable.engineering"

# make the working repo
git clone aoc-inputs modified-aoc-inputs

i=1
while [ $i -ne 26 ]
do
  padded=`printf %03d $i`
  target="modified-aoc-inputs/2021/day_${padded}"
  mkdir -p $target

  # Find all of the relevant input files. This can't really be generic
  # since everyone sort of stores these in their own way

  # mattcl
  find mattcl/examples -name "day_${padded}/input" -exec cp "{}" "${target}/input-mattcl" \;

  # lanjian
  padded=`printf %02d $i`
  find lanjian/inputs -name "day_${padded}" -exec cp "{}" "${target}/input-lanjian" \;

  # nathanwang2
  find nathanwang2 -name "day${i}/*.txt" -exec cp "{}" "${target}/input-nathanwang2" \;

  i=`expr $i + 1`
done

cd modified-aoc-inputs

git add .

git diff --quiet || git commit -am "automated: updated inputs from sources"
