#!/bin/sh
set -e

CUR=$(pwd)
INPUTS="${CUR}/aoc-inputs/2022"

echo "unpacking lanjian examples"
tar -xvf repo/aoc-2022-lanjian.tar.gz
mv aoc-2022-lanjian lanjian

# inputs look like
# aoc-inputs/year/day/files
export AOC_OUTPUT_JSON=true
i=1
while [ $i -ne 26 ]
do
  echo ""
  echo "--- Checking inputs for day ${i} ---"

  padded=`printf %03d $i`
  input_dir="${INPUTS}/day_${padded}"
  solutions="${input_dir}/solutions.json"
  export SOLUTION_FILE="${solutions}"

  if [ ! -d "${input_dir}" ]; then
    echo "no inputs for day ${i}, breaking"
    break
  fi

  input_list=$(find "${input_dir}" -name "input-*" -exec basename {} \;)
  echo "detected the following inputs for day ${i}: ${input_list}"

  var_prefix="AOC_INPUT=${input_dir}"

  # get the list of "executables"
  short_padded=`printf %02d $i`
  lanjian_candidate=$(find lanjian -name "day_${short_padded}")

  if [ -z $lanjian_candidate ]; then
    echo "no solution implemented for day ${i}"
    break
  fi

  for name in $input_list
  do
    export INPUT_NAME="${name}"
    echo "Checking ${name}"
    solution=$(AOC_INPUT="${input_dir}/${name}" $lanjian_candidate)
    echo "${solution}"
    if [ ! -f "${solutions}" ]; then
      echo "no solutions for day ${i}, skipping check"
    else
      echo "checking solution against recorded solution"
      echo "${solution}" | python ci/scripts/check_solution.py
    fi
    echo ""
  done

  # un-tar any compressed files, if necessary
  find "${input_dir}" -type f -name "*.tar.gz" -exec tar -xvf {} -C "${input_dir}" \; || true

  # large benchmarks
  large_input_list=$(find "${input_dir}" -type f -regextype sed -regex ".*/challenge-input-[^.]*" -exec basename {} \;)
  echo "detected the following challenge inputs for day ${i}: ${large_input_list}"
  for name in $large_input_list
  do
    export INPUT_NAME="${name}"
    echo "Checking ${name}"
    solution=$(AOC_INPUT="${input_dir}/${name}" $lanjian_candidate)
    echo "${solution}"
    if [ ! -f "${solutions}" ]; then
      echo "no solutions for day ${i}, skipping check"
    else
      echo "checking solution against recorded solution"
      set +e
      echo "${solution}" | python ci/scripts/check_solution.py
      set -e
    fi
    echo ""
  done

  i=`expr $i + 1`
done
